[package]
name = "configler-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "configler_core"

[dev-dependencies]
cargo-audit.workspace = true
rstest.workspace = true

[dependencies]
dyn-clone = "1.0.17"
regex = "1.11.1"
